Return-Path: <ciphershed-bounce@freelists.org>
Received: from smtp629.redcondor.net (smtp629.redcondor.net [208.80.206.29])
	by mail.pdinc.us (8.12.11.20060308/8.12.11) with ESMTP id s5OHbWKc010207
	for <jpyeron@pdinc.us>; Tue, 24 Jun 2014 13:48:59 -0400
Received: from turing.freelists.org ([206.53.239.180])
          by smtp629.redcondor.net ({45c2894d-6d4c-4ec0-b395-66c345bdc827})
          via TCP (inbound) with ESMTP id 20140624174858369
          for <jpyeron@pdinc.us>;
          Tue, 24 Jun 2014 17:48:58 +0000
X-RC-FROM: <ciphershed-bounce@freelists.org>
X-RC-RCPT: <jpyeron@pdinc.us>
Received: from localhost (localhost [127.0.0.1])
	by turing.freelists.org (Avenir Technologies Mail Multiplex) with ESMTP id 7AD882E2BB;
	Tue, 24 Jun 2014 13:48:54 -0400 (EDT)
X-Virus-Scanned: Debian amavisd-new at turing.freelists.org
Received: from turing.freelists.org ([127.0.0.1])
	by localhost (turing.freelists.org [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id u+PlbXfV+tcb; Tue, 24 Jun 2014 13:48:54 -0400 (EDT)
Received: from turing.freelists.org (localhost [127.0.0.1])
	by turing.freelists.org (Avenir Technologies Mail Multiplex) with ESMTP id 5ADEB2E2BA;
	Tue, 24 Jun 2014 13:48:53 -0400 (EDT)
Received: with ECARTIS (v1.0.0; list ciphershed); Tue, 24 Jun 2014 13:48:53 -0400 (EDT)
X-Original-To: ciphershed@freelists.org
Delivered-To: ciphershed@freelists.org
Received: from localhost (localhost [127.0.0.1])
	by turing.freelists.org (Avenir Technologies Mail Multiplex) with ESMTP id 364CF2E2BB
	for <ciphershed@freelists.org>; Tue, 24 Jun 2014 13:48:53 -0400 (EDT)
X-Virus-Scanned: Debian amavisd-new at turing.freelists.org
Received: from turing.freelists.org ([127.0.0.1])
	by localhost (turing.freelists.org [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id W9huR4prL1d1 for <ciphershed@freelists.org>;
	Tue, 24 Jun 2014 13:48:53 -0400 (EDT)
Received: from mail.pdinc.us (mail.pdinc.us [67.90.184.27])
	by turing.freelists.org (Avenir Technologies Mail Multiplex) with ESMTP id E53CD2E2BA
	for <ciphershed@freelists.org>; Tue, 24 Jun 2014 13:48:23 -0400 (EDT)
Received: from black (nsa1.pdinc.us [67.90.184.2])
	(authenticated bits=0)
	by mail.pdinc.us (8.12.11.20060308/8.12.11) with ESMTP id s5OHmNAo010279
	for <ciphershed@freelists.org>; Tue, 24 Jun 2014 13:48:23 -0400
From: "Jason Pyeron" <jpyeron@pdinc.us>
To: <ciphershed@freelists.org>
References: <3E916F1A3A5343EE87216120BCD5A80C@black><CADfK3RW3ZS9bdxFXz6Afye-AN4k3orppoB9a-eNVX9=trrLt5g@mail.gmail.com><54FA7F498E0D4C1490EAD6E0A44505C4@black><CADfK3RVidP_7aH2C6ROpu5H+_txGgBcekSTBs9V1yRv1WCVwkw@mail.gmail.com> <CADiibPHLVJZZbu8OTFFEzX0Xj4sCjSuHTve-Tjk8Ppx0f4CoHQ@mail.gmail.com> <4719CA6B659B4BA1B936DB57A1153233@black>
Subject: [ciphershed] Re: Git logistics
Date: Tue, 24 Jun 2014 13:48:19 -0400
Organization: PD Inc
Message-ID: <93AEA10447FE483ABE6884D3DAE80B7B@black>
X-Mailer: Microsoft Office Outlook 11
MIME-Version: 1.0
In-Reply-To: <4719CA6B659B4BA1B936DB57A1153233@black>
Thread-Index: Ac+P0iaRnPxE1ZLlQBWWpFCmjntjDAAAEIbAAAB5FXA=
Content-Type: multipart/signed;
	micalg=SHA1;
	protocol="application/x-pkcs7-signature";
	boundary="----=_NextPart_000_0070_01CF8FB2.F3901350"
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.3790.4913
X-archive-position: 567
X-ecartis-version: Ecartis v1.0.0
Sender: ciphershed-bounce@freelists.org
Errors-to: ciphershed-bounce@freelists.org
X-original-sender: jpyeron@pdinc.us
Precedence: normal
Reply-To: ciphershed@freelists.org
List-help: <mailto:ecartis@freelists.org?Subject=help>
List-unsubscribe: <ciphershed-request@freelists.org?Subject=unsubscribe>
List-software: Ecartis version 1.0.0
List-Id: ciphershed <ciphershed.freelists.org>
X-List-ID: ciphershed <ciphershed.freelists.org>
List-subscribe: <ciphershed-request@freelists.org?Subject=subscribe>
List-owner: <mailto:compul@coletteral.net>
List-post: <mailto:ciphershed@freelists.org>
List-archive: <http://www.freelists.org/archives/ciphershed>
X-list: ciphershed

This is a multi-part message in MIME format.

------=_NextPart_000_0070_01CF8FB2.F3901350
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

> -----Original Message-----
> From: Jason Pyeron
> Sent: Tuesday, June 24, 2014 13:39
> 
> 
<snip/>
> 
> On a side note - I am going to generate a temporary GPG key, 
> to use while I am
> hacking GPG to use my smart card. I will post this 
> new/temporary key and sign
> (S/MIME) it with my smart card.

See: http://pgp.mit.edu/pks/lookup?op=get&search=0x8D6B5984DA0848AD

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFOpuQEBCACsdBxA5fEXxv+OowbNNQYzrM3wPpJBhBCxRYM1F+iyqhBw9iq/
sNdm0Q7BPloK9w26jZHuUdSAoQsVA+XrdfrGqPRc3FDLDMxXNNeAXUmtpBObEsxu
PHetKt2wljln//Nm8GEww6OLy6TbsB9h9goHPEAU3ijDWtvfrrcBSk78Xh7c3hyv
D8/1YQcc3LtJHER/plv1jSbGja3V4Ux2oX60BrrMU9g8DYPlgCdkvfhkn3tjrAAt
TobcpbA4gO5q1GH8Xj75NnXBwyRCYmhrzU+nUZZmMS6tb86SNcA7r7LWLtbcFtoq
M9ZQS8YFbMZOt1Zv5ddGpUpittOFGscFN9QFABEBAAG0H0phc29uIFB5ZXJvbiA8
anB5ZXJvbkBwZGluYy51cz6JAT4EEwECACgFAlOpuQECGwMFCQCeNAAGCwkIBwMC
BhUIAgkKCwQWAgMBAh4BAheAAAoJEI1rWYTaCEit2l0IAIxNvZ5xbLSsTGe7eMlt
fIB1bJrzzI46kgnd3e/m0hjL6QiFXMuPFFIQY/+S2Xj34TqtDz5BTdFkAwJqKHOU
py00xM+XBP/luT8X1lUj0ya462T2rZQpBPgG4BWxblS4Lj5dv85YK8T7UuoXSgV3
I+elNyVnqB5FNpQT63/K1RHe7pC1x8i+vQ499Sr0M90HIgZWcV1ZqIq9agSrde37
OmbOx9u3COQrv9RtG9+a/6ZtOi3RCBe+kY6tHP9m1loWqHw+5YDlRyKBauPlApyJ
4X6bxO9S8EHfAVuFeUYwyzkzR6HxcLoyOcYUiWqf7iG+EqedeWSXkDeDqTtRGROm
/aq5AQ0EU6m5AQEIAKN4R7qEDff4Lzone4z7EXc0HVoLyCGzEUtgjFhw3rKX+e2k
7caMhMtDDBb1sGyK68NlbXt2TaSbUbMSJ5w0c6Ve/oOD3Drv6u8HCTpup1kWGziz
cX8F4Z38TVhktpGSerfb9nw6qZV9jpsCJO5upxYb/84YSiR840vmhoqJdWG6FDF8
OkGdSSynebpIN5Tmgebl0j+d6aXT7aRM4FhbyFQFIq1vQQwO87jmnY7lKPafo78J
GBQc8acTjbeTC2lmM/0F8z2465PjprrK5uhBywGkSVlRgCXev79CmvHd7LAu99v5
AAtbGJ0xtL5FwG+heM4dlk8XoK9QG6fhVenN3UUAEQEAAYkBJQQYAQIADwUCU6m5
AQIbDAUJAJ40AAAKCRCNa1mE2ghIrZm+B/0UmYfLFI+72nIRFPq4qPWftR//Dhvf
OTlta1YDr5Y+ejdTRqTvlR8nAmqJki2Dn56JDYylvIMdVo1Qsnk59S4dc4tbwHFp
QIqykfo/UhxzL+7OLqrKNzpspMaTvdA2XUxv+iqPElNFoNqHVPbhTkoHv+I+6Qpq
7NV5rqK3AXESQkbfCbzQ7ZxU4ZgE0TlM+jwjqAPXaAo6Fg0Fxdl90HUgFB4Exl+x
n2Q3EZ60pLXsTJpjzMiFD/LYfS+kqeDgCsQaIFOEimioaYLnBWwbe4zOK8N3uYnL
xphHSBMYjYj0z8k4Zs5zGi3C/RUig9eJm1zU8xeyOQ9+y961aK7Dek7L
=UQIJ
-----END PGP PUBLIC KEY BLOCK-----

--
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
-                                                               -
- Jason Pyeron                      PD Inc. http://www.pdinc.us -
- Principal Consultant              10 West 24th Street #100    -
- +1 (443) 269-1555 x333            Baltimore, Maryland 21218   -
-                                                               -
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
This message is copyright PD Inc, subject to license 20080407P00.

------=_NextPart_000_0070_01CF8FB2.F3901350
Content-Type: application/x-pkcs7-signature;
	name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
	filename="smime.p7s"

MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAQAAoIIWpTCCBDow
ggMioAMCAQICAQUwDQYJKoZIhvcNAQEFBQAwTTELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4g
R292ZXJubWVudDEMMAoGA1UECxMDRUNBMRYwFAYDVQQDEw1FQ0EgUm9vdCBDQSAyMB4XDTA4MDQw
NDE0MjQ0OVoXDTI4MDMzMDE0MjQ0OVowTTELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4gR292
ZXJubWVudDEMMAoGA1UECxMDRUNBMRYwFAYDVQQDEw1FQ0EgUm9vdCBDQSAyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs5DYHu+a7W5HsUZhRo2jVgicSjLHRfLSpKRmvn49l4Dv6ddr
6eDAO43i+BL6EzWkzVqGi7DQLzSM9wXth2+nMBfQFsZYRr2V+VYaiNROHn5YHxuicxWdXosGJBN2
PJ9gYq2wtfTgJMFT99kcNx3mPPD60/H5oZjxN4XYzwJg8KA4lEtRKAnCF/xApGF5DrSMGyCCYvXk
mtYpijb6H4HAoRExS/5W/di/UZMnWdr1gz5EpN/VIGfrnwCn+94xtmMxHD33HGwJjX/0upyofB8B
xoBtAQHYN6j+LX0rwsvW6Zy6lI12Ft7MgXUEe0F3FWUVyawAtr/rHNy5jWQt/zXbxQIDAQABo4IB
IzCCAR8wHQYDVR0OBBYEFO3kh9AnxFDmhDr3zPfrOkn8Uk4hMA4GA1UdDwEB/wQEAwIBhjAPBgNV
HRMBAf8EBTADAQH/MIHcBggrBgEFBQcBCwSBzzCBzDBDBggrBgEFBQcwBYY3aHR0cDovL2NybC5n
ZHMuZGlzYS5taWwvZ2V0SXNzdWVkQnk/RUNBJTIwUm9vdCUyMENBJTIwMjCBhAYIKwYBBQUHMAWG
eGxkYXA6Ly9jcmwuZ2RzLmRpc2EubWlsL2NuJTNkRUNBJTIwUm9vdCUyMENBJTIwMiUyY291JTNk
RUNBJTJjbyUzZFUuUy4lMjBHb3Zlcm5tZW50JTJjYyUzZFVTP2Nyb3NzQ2VydGlmaWNhdGVQYWly
O2JpbmFyeTANBgkqhkiG9w0BAQUFAAOCAQEASswb54WIkyPZub7PuvE1lMFLPBNwXYMuTn7BVg8t
wX4fDend/gKZfGDjhqq5hiPDF37HEQ/j0EJWoxzzcI+xiJG1vA6JJWbIP182Kg4+tmdAjD1A36di
4DgY+iRtLSPTwLh0XpVEVHohlw9azcP8lT0iIhXdGGBdhTepTfeB/L1KpliMT7/HZaH/4tM0SBoX
ATLyhPPeBbJkSZg3zSH1qIFbZMXafFiwYWEfrcCt7TS2lKvHnOxllymFlJQzxDUkiz3N/Dcqu/qk
thuQ8pVXF0jg76mdrQDisWTZZ3kRg7ma6AsyNs4gZ+N6bUvqXlPlLzBB3fjlVJ2p12nGddlFRzCC
BXAwggRYoAMCAQICAQ4wDQYJKoZIhvcNAQEFBQAwTTELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1Uu
Uy4gR292ZXJubWVudDEMMAoGA1UECxMDRUNBMRYwFAYDVQQDEw1FQ0EgUm9vdCBDQSAyMB4XDTEx
MDYwMTEzNDEzMFoXDTE3MDUzMDEzNDEzMFowcDELMAkGA1UEBhMCVVMxGDAWBgNVBAoTD1UuUy4g
R292ZXJubWVudDEMMAoGA1UECxMDRUNBMSIwIAYDVQQLExlDZXJ0aWZpY2F0aW9uIEF1dGhvcml0
aWVzMRUwEwYDVQQDEwxPUkMgRUNBIEhXIDQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDge/Z9Vb4GLw94fCmCkOc2BJGg5Qv2UyNGoaNifHPne2x/YJaNF/rUNaSZql/Dc5TV4YdDtNIj
ZXDRTL1zjrozbZRCpZzh00mowhitYrdl4OdVFbLRNbQtm+hab0VWeEe/Jvlth9GPmEaAHcbLIF1q
x/1bcXjEp8BE84p+WoxXniVZf3RBlv0FOt48pIxwbb3pOmITd1US5sPiRoQ7KTjVJ/eV68tftNHa
/kLuUy+KjbQoNtGng71BClqBaU3YhXP1Sfe/Spu0iOnH7/hQ4OE/WC2bbl50Xrm+VTmfhMFyxxxb
dspGN86k6YQmiSAqjq0wYWaxdRRIsnt7T49UHr9VAgMBAAGjggI2MIICMjASBgNVHRMBAf8ECDAG
AQH/AgEAMA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUW1TB31t33S3052BtEbiayFwM5+kwHwYD
VR0jBBgwFoAU7eSH0CfEUOaEOvfM9+s6SfxSTiEwMwYDVR0gBCwwKjAMBgpghkgBZQMCAQwBMAwG
CmCGSAFlAwIBDAIwDAYKYIZIAWUDAgEMAzCBwAYDVR0fBIG4MIG1MCygKqAohiZodHRwOi8vY3Js
LmRpc2EubWlsL2NybC9FQ0FST09UQ0EyLmNybDCBhKCBgaB/hn1sZGFwOi8vY3JsLmdkcy5kaXNh
Lm1pbC9jbiUzZEVDQSUyMFJvb3QlMjBDQSUyMDIlMmNvdSUzZEVDQSUyY28lM2RVLlMuJTIwR292
ZXJubWVudCUyY2MlM2RVUz9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0O2JpbmFyeTCB0wYIKwYB
BQUHAQEEgcYwgcMwOgYIKwYBBQUHMAKGLmh0dHA6Ly9jcmwuZGlzYS5taWwvaXNzdWVkdG8vRUNB
Uk9PVENBMl9JVC5wN2MwgYQGCCsGAQUFBzAChnhsZGFwOi8vY3JsLmdkcy5kaXNhLm1pbC9jbiUz
ZEVDQSUyMFJvb3QlMjBDQSUyMDIlMmNvdSUzZEVDQSUyY28lM2RVLlMuJTIwR292ZXJubWVudCUy
Y2MlM2RVUz9jcm9zc0NlcnRpZmljYXRlUGFpcjtiaW5hcnkwDQYJKoZIhvcNAQEFBQADggEBAAgE
rwyRj0AJ3jSCiUPgB2NyvxQhKhjfcNXSZWCQB7Fm7Dz+Z7NwNmDtCUTzr1jjLWF+raQe/2wRqVqH
RRIP/43fg4Y4DczjW9l2AghSJwssI0mw+VvHKwMSfffRV5VkUUaLHjlzBMFKm+U6I8IYfXRDlivp
b4jDOsjVO4MbEE4A6qT+4xQkyKvu5bJhNOUMhmZH+6WfLKS+q4ZDQH8RUYPNFxB6MS5sQFPP+d7w
og8grAsJD3s3SZAImKWWOaYJK8975BjMGK/LWLAnsFAneKTCH15EfEHsKNyK+lhMATH0BugSey8e
OipODRXrXfNpQcBpNoxTgn9sR0pYBffWXiMwggZQMIIFOKADAgECAgJgijANBgkqhkiG9w0BAQUF
ADBwMQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNFQ0Ex
IjAgBgNVBAsTGUNlcnRpZmljYXRpb24gQXV0aG9yaXRpZXMxFTATBgNVBAMTDE9SQyBFQ0EgSFcg
NDAeFw0xNDAzMjExNDQ5NTVaFw0xNTAzMjExNDQ5NTVaMIGDMQswCQYDVQQGEwJVUzEYMBYGA1UE
ChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNFQ0ExDDAKBgNVBAsTA09SQzEPMA0GA1UECxMG
UEQgSW5jMS0wKwYDVQQDEyRQeWVyb24uSmFzb24uSi5PUkMxMDAwMDQwMDA5LkVuY3J5cHQwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCHVGq6phwNUEI94zOPAen5rvUdObUTzuwHMwEw
L9wmvWktZ0Zj8ONcWrYLfr+H9YSEf3H0rKbJinu8YXqP0KwKZPm7+5zMqfHW3nE95IyKSYaq9YiM
Fi1VBKijmxEdO5NZCpFANtCaa0GUI78GI6PrBK9Q2qTTSU281cmr4TXSBfg+D6c9Af+ZPCsqJnEi
nv75M4ujeYkgF5Q+yFY6xCfPWlOPSjkpCyFuDqLG7G8mI4BHTuCiPNazURh7uQVidqrm6lZgco+M
QifyvEw2FMKKI59YYTMuukwCmZXZHY7xgUsx1zY3UofZ7G75xCSIa+KIg3WiTwF4ZDlvkGbzJxgn
AgMBAAGjggLeMIIC2jAfBgNVHSMEGDAWgBRbVMHfW3fdLfTnYG0RuJrIXAzn6TAdBgNVHQ4EFgQU
o/cER+2FSXj3xSAACMzkFCxkMLYwggEjBggrBgEFBQcBAQSCARUwggERMB4GCCsGAQUFBzABhhJo
dHRwOi8vZXZhLm9yYy5jb20wMgYIKwYBBQUHMAKGJmh0dHA6Ly9lY2Eub3JjLmNvbS9jYUNlcnRz
L0VDQS1IVzQucDdjMIG6BggrBgEFBQcwAoaBrWxkYXA6Ly9lY2EtZHMub3JjLmNvbS9jbiUzZE9S
QyUyMEVDQSUyMEhXJTIwNCUyY291JTNkQ2VydGlmaWNhdGlvbiUyMEF1dGhvcml0aWVzJTJjb3Ul
M2RFQ0ElMmNvJTNkVS5TLiUyMEdvdmVybm1lbnQlMmNjJTNkVVM/Y0FDZXJ0aWZpY2F0ZTtiaW5h
cnksY3Jvc3NDZXJ0aWZpY2F0ZVBhaXI7YmluYXJ5MA4GA1UdDwEB/wQEAwIFIDAbBgNVHREEFDAS
gRBqcHllcm9uQHBkaW5jLnVzMDMGA1UdIAQsMCowDAYKYIZIAWUDAgEMATAMBgpghkgBZQMCAQwC
MAwGCmCGSAFlAwIBDAMwgfEGA1UdHwSB6TCB5jAroCmgJ4YlaHR0cDovL2VjYS5vcmMuY29tL0NS
THMvT1JDRUNBSFc0LmNybDCBtqCBs6CBsIaBrWxkYXA6Ly9lY2EtZHMub3JjLmNvbTozODkvY24l
M0RPUkMlMjBFQ0ElMjBIVyUyMDQlMkMlMjBvdSUzRENlcnRpZmljYXRpb24lMjBBdXRob3JpdGll
cyUyQyUyMG91JTNERUNBJTJDJTIwbyUzRFUuUy4lMjBHb3Zlcm5tZW50JTJDJTIwYyUzRFVTP2Nl
cnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q7YmluYXJ5MBsGA1UdCQQUMBIwEAYIKwYBBQUHCQQxBBMC
VVMwDQYJKoZIhvcNAQEFBQADggEBAMHBMK1AgK67iB22i3RXU9GmWaWr3EN57rSCDL+KqBvkZqBm
K6NpnB+ka3kfhnv6KQCno2cQlup6miwd43td7J/WVTYxQCHhBWpf163SIl50ZvbtmNU/eFkhEu+Q
x+NQ6U8vf8Tur6RXheMlBW34FwJ3VrxpuF1vPg9ntUGfNl36sgcbNjc7rL/t8EhgXGVyKRQI4X4D
ZBw+txM425OFoY2RRkuf1rB8EMA1HPUsAMRt5rSgLLplt2mrbrMaiG7cO0SFQjgAGOgb2ZXrX/Mp
POu4R78vjhQacrzXSoAHoMG72QJ9C1Kn9FyhjYhDzSIsffQF48QRq1bciseiOBeSnh8wggabMIIF
g6ADAgECAgJgiTANBgkqhkiG9w0BAQUFADBwMQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBH
b3Zlcm5tZW50MQwwCgYDVQQLEwNFQ0ExIjAgBgNVBAsTGUNlcnRpZmljYXRpb24gQXV0aG9yaXRp
ZXMxFTATBgNVBAMTDE9SQyBFQ0EgSFcgNDAeFw0xNDAzMjExNDQ4NDVaFw0xNTAzMjExNDQ4NDVa
MH4xCzAJBgNVBAYTAlVTMRgwFgYDVQQKEw9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0VDQTEM
MAoGA1UECxMDT1JDMQ8wDQYDVQQLEwZQRCBJbmMxKDAmBgNVBAMTH1B5ZXJvbi5KYXNvbi5KLk9S
QzEwMDAwNDAwMDkuSUQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCIL0F8IDr6w0UP
8SQyeCpzFSQCTX+1oekpZImxMYChSJaRY5NQUlRHh9gnTM1r49repFVI+HFOJogavB0zUS3TVXp0
r23kwgHWAjiiyagdwsfEgWObIx4FLUaVOYNYO777kxk/Nydo7S1+4qrV0DFpLuQC1Gsh9F4s8+9F
dUNjkLXjf04fBufMz3ks+O271KnbZKtdmroWtzUxO2w8B90JCQJQbOAwtiyXC6KTCf5QcucHUX04
fyBbKJxItSF13MAIxViGzK+/eWYdajW5Ni6EQ10LpOgJwCzYCCZONrPbFJ+EklJCF3DwzlnMoID9
zYFwVqSExIFV6uUlZ/xAOiaNAgMBAAGjggMvMIIDKzAfBgNVHSMEGDAWgBRbVMHfW3fdLfTnYG0R
uJrIXAzn6TAdBgNVHQ4EFgQUnGL5UXepgybvXuqzlqGkL1YvyH4wggEjBggrBgEFBQcBAQSCARUw
ggERMB4GCCsGAQUFBzABhhJodHRwOi8vZXZhLm9yYy5jb20wMgYIKwYBBQUHMAKGJmh0dHA6Ly9l
Y2Eub3JjLmNvbS9jYUNlcnRzL0VDQS1IVzQucDdjMIG6BggrBgEFBQcwAoaBrWxkYXA6Ly9lY2Et
ZHMub3JjLmNvbS9jbiUzZE9SQyUyMEVDQSUyMEhXJTIwNCUyY291JTNkQ2VydGlmaWNhdGlvbiUy
MEF1dGhvcml0aWVzJTJjb3UlM2RFQ0ElMmNvJTNkVS5TLiUyMEdvdmVybm1lbnQlMmNjJTNkVVM/
Y0FDZXJ0aWZpY2F0ZTtiaW5hcnksY3Jvc3NDZXJ0aWZpY2F0ZVBhaXI7YmluYXJ5MA4GA1UdDwEB
/wQEAwIGwDApBgNVHSUEIjAgBggrBgEFBQcDAgYIKwYBBQUHAwQGCisGAQQBgjcUAgIwQQYDVR0R
BDowOIEQanB5ZXJvbkBwZGluYy51c6AkBgorBgEEAYI3FAIDoBYMFE9SQzEwMDAwNDAwMDlARE9E
RUNBMDMGA1UdIAQsMCowDAYKYIZIAWUDAgEMATAMBgpghkgBZQMCAQwCMAwGCmCGSAFlAwIBDAMw
gfEGA1UdHwSB6TCB5jAroCmgJ4YlaHR0cDovL2VjYS5vcmMuY29tL0NSTHMvT1JDRUNBSFc0LmNy
bDCBtqCBs6CBsIaBrWxkYXA6Ly9lY2EtZHMub3JjLmNvbTozODkvY24lM0RPUkMlMjBFQ0ElMjBI
VyUyMDQlMkMlMjBvdSUzRENlcnRpZmljYXRpb24lMjBBdXRob3JpdGllcyUyQyUyMG91JTNERUNB
JTJDJTIwbyUzRFUuUy4lMjBHb3Zlcm5tZW50JTJDJTIwYyUzRFVTP2NlcnRpZmljYXRlUmV2b2Nh
dGlvbkxpc3Q7YmluYXJ5MBsGA1UdCQQUMBIwEAYIKwYBBQUHCQQxBBMCVVMwDQYJKoZIhvcNAQEF
BQADggEBAIdJ0/H8HR4YWUR+61QOVO7TZEcQ42QYzLU6910C8voTytaHKu1SWNMbsBaw/mmYK/ez
+mFuXO39eRUYmSoaZk9KmvTG4kALL21ETRdAIUmgLl039qDP3ASLyPHa9KLleJCmxNpK6QnRhvqp
MItvJX9Ly8nUdRTs9fiy5am4+Zh0lNaQNeelW70pEEWPbR1EXyD/vfueIccOic/A9NrGf7P1MjgF
qAhUbPuTwD5DiCcxItvi6uiIx3ykyM45TzEZSKZSWMwxMY3UGno4oEEtiJSEOhWYAj6hypGgm8xE
wAb/AGWgDYwdRl5zQm6v+f4OdLm85iX3oaztaaj+IKarJIcxggN5MIIDdQIBATB2MHAxCzAJBgNV
BAYTAlVTMRgwFgYDVQQKEw9VLlMuIEdvdmVybm1lbnQxDDAKBgNVBAsTA0VDQTEiMCAGA1UECxMZ
Q2VydGlmaWNhdGlvbiBBdXRob3JpdGllczEVMBMGA1UEAxMMT1JDIEVDQSBIVyA0AgJgiTAJBgUr
DgMCGgUAoIIB2DAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNDA2
MjQxNzQ4MTdaMCMGCSqGSIb3DQEJBDEWBBSJfE7VwxpJ/HRJx3rxeNAKdmbbHTBnBgkqhkiG9w0B
CQ8xWjBYMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIAgDANBggqhkiG9w0DAgIBQDAHBgUrDgMC
BzANBggqhkiG9w0DAgIBKDAHBgUrDgMCGjAKBggqhkiG9w0CBTCBhQYJKwYBBAGCNxAEMXgwdjBw
MQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zlcm5tZW50MQwwCgYDVQQLEwNFQ0ExIjAg
BgNVBAsTGUNlcnRpZmljYXRpb24gQXV0aG9yaXRpZXMxFTATBgNVBAMTDE9SQyBFQ0EgSFcgNAIC
YIowgYcGCyqGSIb3DQEJEAILMXigdjBwMQswCQYDVQQGEwJVUzEYMBYGA1UEChMPVS5TLiBHb3Zl
cm5tZW50MQwwCgYDVQQLEwNFQ0ExIjAgBgNVBAsTGUNlcnRpZmljYXRpb24gQXV0aG9yaXRpZXMx
FTATBgNVBAMTDE9SQyBFQ0EgSFcgNAICYIowDQYJKoZIhvcNAQEBBQAEggEAHnmCfMHcnaCAPYKZ
W6g0sDVRXbCKKfXdKi2cCHUpAcavdKfmxczCAxku6VQVLeLMnWa00tP7OVX/fwgmouW6IshQMJmL
Xt98qKfXL6m3u3cKQr7jHyoibn0EY4njgjSoyJ2t+vt/ism5fTej6wrg56URA8YrqRVA2y6uRvxc
JxtQ1DZAjy5/RZtkF/mM/yBPDxXpFbLE2PNu8etJ52k0hM9IGCr9ZAmWNcxsF+yBajBA7TNu/3Ju
xdn+cYZ1cjVpNRbY4bA7ROwDJJHMk229WviHDH7nnPDR+rp8E9osH9oZ0ForEQFxoTrAMC3c3TWd
UTFy2g6buixLtJZ8cABv2gAAAAAAAA==

------=_NextPart_000_0070_01CF8FB2.F3901350--



