
include 	../Boot/EFI/Makefile.inc

LOCALINC        = ../Boot/EFI/include
EFIINCS         = -I$(LOCALINC) -I$(EFIINC) $(OTHERINCS)
CFLAGS += -DTC_WINDOWS_BOOT

OBJS            = Aescrypt.o  Aeskey.o  Aestab.o  Blowfish.o  Cast.o  Rmd160.o  Serpent.o  Sha1.o  Sha2.o  Twofish.o

%.o:	%.c %.h

all: $(OBJS)

	
PHONY: clean

clean:
	rm -f *.so *.o *~
