#ifndef _cs_rc_version_h_
#define _cs_rc_version_h_
#define _RC_INC_FILEVERSION_VALUE 0,7,4,0
#define _RC_INC_PRODUCTVERSION_VALUE _RC_INC_FILEVERSION_VALUE
#define _RC_INC_FILEVERSION_VALUE_STR "0.7.4.0"
#define _RC_INC_PRODUCTVERSION_VALUE_STR _RC_INC_FILEVERSION_VALUE_STR
#endif
