
include 	../Boot/EFI/Makefile.inc

LOCALINC        = ../Boot/EFI/include
EFIINCS         = -I$(LOCALINC) -I$(EFIINC) $(OTHERINCS)
CFLAGS += -DTC_WINDOWS_BOOT

OBJS            = Crc.o Xts.o GfMul.o Pkcs5.o Endian.o

%.o:	%.c %.h

all: $(OBJS)

PHONY: clean

clean:
	rm -f *.so *.o *~
